from odoo import api, fields, models


class HrApp(models.Model):
    _inherit = 'hr.applicant'
    re_skill = fields.Char(string="Skill", required=False,readonly=True,default="Relevant educational background" )
    skill_re_s = fields.Selection(string="Grade", selection=[('rel', 'Related'), ('oc', 'Only courses'), ('nrel', 'Not related') ], required=False, )
    ro_skill = fields.Char(string="Skill", required=False,readonly=True,default="Related work experience " )
    skill_ro_s = fields.Selection(string="Grade", selection=[('per', 'Perfectly matched'), ('mat', 'Matched'), ('poor', 'Poor Match') ], required=False, )
    v_skill = fields.Char(string="Skill", required=False,readonly=True,default="Verbal communication skills " )
    skill_v_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    w_skill = fields.Char(string="Skill", required=False,readonly=True,default="Written communication skills" )
    skill_w_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    a_skill = fields.Char(string="Skill", required=False,readonly=True,default="Attention to detail " )
    skill_a_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    t_skill = fields.Char(string="Skill", required=False,readonly=True,default="Takes initiative" )
    skill_t_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    i_skill = fields.Char(string="Skill", required=False,readonly=True,default="Integrity" )
    skill_i_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    c_skill = fields.Char(string="Skill", required=False,readonly=True,default="Cooperation" )
    skill_c_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    s_skill = fields.Char(string="Skill", required=False,readonly=True,default="Stress tolerance" )
    skill_s_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    l_skill = fields.Char(string="Skill", required=False,readonly=True,default="Learning ability " )
    skill_l_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    in_skill = fields.Char(string="Skill", required=False,readonly=True,default="Interpersonal skills" )
    skill_in_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    pro_skill = fields.Char(string="Skill", required=False,readonly=True,default="Professional demeanor " )
    skill_pro_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    ca_skill = fields.Char(string="Skill", required=False,readonly=True,default="Candidate stability" )
    skill_ca_s = fields.Selection(string="Grade", selection=[('ex', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'),('not', 'Not observed') ], required=False, )
    att_skill = fields.Char(string="Skill", required=False,readonly=True,default="Attitude towards his position" )
    skill_att_s = fields.Selection(string="Grade", selection=[('vp', 'Very passionate'), ('pas', 'Passionate'), ('poor', 'poor passion'),('not', 'Not observed') ], required=False, )
    atc_skill = fields.Char(string="Skill", required=False,readonly=True,default="Attitude towards our company " )
    skill_atc_s = fields.Selection(string="Grade", selection=[('vi', 'Very interested'), ('in', 'Interested'), ('poor', ' Poor interest'),('not', 'Not observed') ], required=False, )
    interview_date = fields.Datetime(string="Interview Date", required=False, )